version: '3.7'

services:

  db-15-33:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - db-15-33

networks:
  db-15-33:
    name: doctrine-postgis-15-33
    driver: bridge
